CITIROC_path : ../CitirocControlSoft/bin
HUL_path     : ../hul-common-lib/install/bin
YAML_path    : ../CIRASAME_calib/yaml_files/cirasame016
CIRASAME_ip  : 192.168.2.116
DAC_scan:
  start : 100
  gap   : 5
  steps : 80
FILE_name    : aaa