CITIROC_path : /home/okarin/cirasame/CitirocControlSoft/bin
HUL_path     : /home/okarin/cirasame/hul-common-lib/install/bin
YAML_path    : /home/okarin/cirasame/CIRASAME_calib/yaml_files/cirasame016
CIRASAME_ip  : 192.168.2.116
DAC_scan:
  start : 100
  gap   : 5
  steps : 80
FILE_name    : aaa