CITIROC_path : /home/okarin/CitirocControlSoft-master/bin
HUL_path     : /home/okarin/hul-common-lib/install_20231212/install/bin
YAML_path    : /home/okarin/cirasame/scaler_automation/yaml_files
CIRASAME_ip  : 192.168.10.16
DAC_scan:
  start : 125
  gap   : 2
  steps : 200
FILE_name    : aaa