CITIROC_path : /home/okarin/cirasame/CitirocControlSoft/bin
HUL_path     : /home/okarin/cirasame/hul-common-lib/install/bin
YAML_path    : /home/okarin/cirasame/CIRASAME_calib/yaml_files
CIRASAME_ip  : 192.168.2.113
DAC_scan:
  start : 100
  gap   : 10
  steps : 60
FILE_name    : aaa